### ISSUE TITLE
Keycloak-js version 7

### ISSUE THREAD

**Issue by xtrasmal** [akoserwal/keycloak-integrations#1]
Hi there,

I noticed you wrote an article about keycloak-js and I followed the link to this repo. 

Could you answer me why all example use keycloak-js version 6.0.1 and not the latest 7.0.0?
And can you explain why the 7.0.0 version seems to dislike being imported?

**Comment by akoserwal** [comment]
@xtrasmal: Sorry for the late response, I'll update the versions

**Comment by akoserwal** [comment]
@xtrasmal: upgraded version to the latest: 8.x.x for angular, vue, & react.
